#!/usr/bin/env bash


main() {
	local version
	version="$(cat VERSION)"
	echo "VERSION: $version"
	version="$(cat git-flux-playground-version)"
	echo "git-flux-playground-version: $version"
	version="@@VERSION@@"
	echo "\@\@VERSION\@\@: $version"
}


main
